CREATE TABLE FORNECEDORES(
	IDFORNECEDOR				UNIQUEIDENTIFIER				PRIMARY KEY,
	NOME						VARCHAR(150)					NOT NULL,
	CNPJ						CHAR(14)						UNIQUE NOT NULL
);

CREATE TABLE CATEGORIAS(
	IDCATEGORIA					UNIQUEIDENTIFIER				PRIMARY KEY,
	DESCRICAO					VARCHAR(150)					NOT NULL
);

CREATE TABLE PRODUTOS(
    IDPRODUTO					UNIQUEIDENTIFIER				PRIMARY KEY,
    NOME						VARCHAR(150)					NOT NULL,
    PRECO						FLOAT							NOT NULL,
    QUANTIDADE					INT								NOT NULL,
    DATACOMPRA					DATETIME						NOT NULL,
    IDFORNECEDOR				UNIQUEIDENTIFIER				NOT NULL,
    IDCATEGORIA					UNIQUEIDENTIFIER				NOT NULL,
    FOREIGN KEY(IDFORNECEDOR)	REFERENCES						FORNECEDORES(IDFORNECEDOR),
    FOREIGN KEY(IDCATEGORIA)	REFERENCES						CATEGORIAS(IDCATEGORIA)
);